name: mern-dev

services:

  server:
    # image: nignx:1-alpine

    build:
      context: /home/safi/main/nginx
      dockerfile: Dockerfile
      
    ports:
      - "80:80"

    # volumes:
    #   - /home/safi/main/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

    develop:
      watch:
        - action: sync+restart
          path: /home/safi/main/nginx/conf.d
          target: /etc/nginx/conf.d
      
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - frontend
      - backend
    networks:
      - network

  frontend:

    # Build Image
    build:
      context: /home/safi/main/javascript/next-app
      dockerfile: docker/Dockerfile.dev

    # Local Image
    # image: next-app-image

    # nginx works with containers port
    # no need to expose
    # ports:
    #   - "3000:3000"

    # extra_hosts:
      # - "nextjs.localhost:127.0.0.1"
      # - "nextjs.localhost:host-gateway"

    # Watch is better then bind
    # volumes:
    #   - type: bind
    #     source: ${PWD}
    #     target: /app

    develop:
      watch:
        - action: sync
          path: /home/safi/main/javascript/next-app
          target: /app
          ignore:
            - node_modules/

    networks:
      - network

    depends_on:
      - backend


  backend:
    build:
      context: /home/safi/main/javascript/express-app
      dockerfile: docker/Dockerfile.dev

    # nginx works with containers port
    # no need to expose
    # ports:
    #   - "3001:3000"
    
    develop:
      watch:
        - action: sync
          path: /home/safi/main/javascript/express-app
          target: /app
          ignore:
            - node_modules/

    networks:
      - network
    
  
networks:
  network: